"""Resilient supervision for chained *interactive* runs.

An interactive chain (`pimm submit --interactive` with ``chain.jobs > 1``) is
driven by a foreground process that ``salloc``s each slot in turn (see
``run_interactive`` in ``submit.py``). Run from a login shell, that driver dies
with the shell / SSH session / login-node reboot, orphaning the whole chain -
no queued job carries on.

This module hosts that driver as a ``scron`` job on the login-node ``cron``
partition instead. ``scron`` does not overlap instances and reschedules across
login-node reboots, so the driver is resurrected (on any login node) within one
tick and resumes from the last checkpoint. Every slot stays interactive;
nothing ever becomes a batch job.

Kept separate from ``submit.py`` on purpose: ``submit.py`` renders/queues a
single launch, this module owns the cross-restart *supervision* lifecycle
(wrapper script + scrontab entry + state).

The driver's own re-invocation of ``pimm submit --interactive`` must run the
foreground chain, not recurse into installing another watchdog; the wrapper
sets ``PIMM_WATCHDOG_CHILD=1`` and ``run_submit`` honours it (see
``submit.run_submit``).

NOTE: This has only been tested on NERSC, which has a `cron` partition.
"""

from __future__ import annotations

import os
import shlex
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any

from .submit import build_slurm_job_name, experiment_config_path
from .utils import ROOT, as_bool

CHILD_ENV = "PIMM_WATCHDOG_CHILD"


# --------------------------------------------------------------------------- #
# Paths / config
# --------------------------------------------------------------------------- #
def _repo_root(cfg: dict[str, Any]) -> Path:
    return Path(str(cfg.get("paths", {}).get("repo_root", ROOT)))


def state_dir(cfg: dict[str, Any], run_name: str) -> Path:
    """Where the wrapper, markers and driver log for a run live (global FS)."""
    return _repo_root(cfg) / "slurm_logs" / "watchdog" / run_name


def _model_dir(cfg: dict[str, Any], run_name: str) -> Path:
    return experiment_config_path(cfg, run_name).parent / "model"


def _watchdog_cfg(cfg: dict[str, Any]) -> dict[str, Any]:
    wd = dict(cfg.get("watchdog") or {})
    wd.setdefault("qos", "cron")
    wd.setdefault("interval_min", 5)
    wd.setdefault("time", "1-00:00:00")
    return wd


# --------------------------------------------------------------------------- #
# Wrapper script rendering
# --------------------------------------------------------------------------- #
_DRIVER_TEMPLATE = r"""#!/bin/bash
# AUTO-GENERATED by `pimm submit --interactive` (chain.jobs > 1). Do not edit by
# hand -- re-run the submit command to regenerate. Hosts the interactive chain
# driver resiliently via scron; every slot is interactive, never batch.
set -uo pipefail

RUN=@@RUN@@
REPO=@@REPO@@
STATE=@@STATE@@
MODELDIR=@@MODELDIR@@
PY=@@PY@@
PIMM=@@PIMM@@
MAX_NOPROGRESS=@@MAXNOPROGRESS@@

DONE="$STATE/DONE"; FAILED="$STATE/FAILED"; LOCK="$STATE/driver.lock"
COUNTER="$STATE/noprogress_count"; DLOG="$STATE/driver.log"
mkdir -p "$STATE"
log() { echo "[$(date '+%F %T')] $*" | tee -a "$DLOG"; }

export PATH="$HOME/.local/bin:/usr/bin:/bin:$PATH"
cd "$REPO" || exit 1

[ -e "$DONE" ]   && { log "chain complete; nothing to do"; exit 0; }
[ -e "$FAILED" ] && { log "chain marked FAILED (persistent crash). To resume: rm $FAILED $COUNTER"; exit 0; }

# Single driver only (scron already serializes; flock guards a manual run too).
exec 9>"$LOCK"
flock -n 9 || { log "another driver holds the lock; exiting"; exit 0; }

ckpt_of() { "$PY" -m pimm.utils.path latest-checkpoint "$MODELDIR" 2>/dev/null; }
ckpt_mtime() { local c; c=$(ckpt_of); [ -n "$c" ] && stat -c %Y "$c" 2>/dev/null || echo 0; }
before=$(ckpt_mtime)

# Resume iff a complete checkpoint already exists (train.sh errors on resume
# with none). A fresh run's first slot starts clean; every later slot resumes.
RESUME=""
[ -n "$(ckpt_of)" ] && RESUME="--chain.resume-first"

# Clear this scron job's own SLURM_* context (keep SLURM_CONF) so the driver's
# salloc is a fresh top-level allocation, not a rejected nested one.
for v in ${!SLURM@}; do [ "$v" = SLURM_CONF ] && continue; unset "$v"; done

HEAD=( @@HEAD_ARRAY@@ )
TAIL=( @@TAIL_ARRAY@@ )
CMD=( "$PIMM" submit "${HEAD[@]}" )
[ -n "$RESUME" ] && CMD+=( "$RESUME" )
[ ${#TAIL[@]} -gt 0 ] && CMD+=( -- "${TAIL[@]}" )

log "starting interactive chain driver on $(hostname) (resume=${RESUME:-no})"
@@CHILD_ENV@@=1 "${CMD[@]}" >>"$DLOG" 2>&1
rc=$?
after=$(ckpt_mtime)
log "driver exited rc=$rc (ckpt_mtime $before -> $after)"

if [ "$rc" -eq 0 ]; then
  touch "$DONE"; : >"$COUNTER"
  log "training completed cleanly -> DONE (chain stops)"
elif [ "$after" -gt "$before" ]; then
  : >"$COUNTER"
  log "made checkpoint progress; next scron tick restarts & resumes"
else
  n=$(( $(cat "$COUNTER" 2>/dev/null || echo 0) + 1 ))
  echo "$n" >"$COUNTER"
  if [ "$n" -ge "$MAX_NOPROGRESS" ]; then
    touch "$FAILED"
    log "$n consecutive exits with no checkpoint progress -> FAILED, not restarting"
  else
    log "no checkpoint progress ($n/$MAX_NOPROGRESS); treating as transient, will retry next tick"
  fi
fi
"""


def _split_argv(raw_argv: list[str]) -> tuple[list[str], list[str]]:
    """Split submit argv into (head, tail) around the ``--`` training separator,
    dropping any user-supplied ``--chain.resume-first`` (the wrapper decides
    resume by checkpoint state) and install-only flags."""
    if "--" in raw_argv:
        i = raw_argv.index("--")
        head, tail = list(raw_argv[:i]), list(raw_argv[i + 1 :])
    else:
        head, tail = list(raw_argv), []
    drop = {"--chain.resume-first", "--chain.resume_first", "--dry-run", "--no-remote"}
    head = [a for a in head if a not in drop]
    return head, tail


def _pimm_executable() -> str:
    return shutil.which("pimm") or os.path.abspath(sys.argv[0])


def render_driver_script(cfg: dict[str, Any], run_name: str, raw_argv: list[str]) -> str:
    """Render the per-run wrapper the scron job executes."""
    head, tail = _split_argv(raw_argv)
    subs = {
        "@@RUN@@": shlex.quote(run_name),
        "@@REPO@@": shlex.quote(str(_repo_root(cfg).resolve())),
        "@@STATE@@": shlex.quote(str(state_dir(cfg, run_name).resolve())),
        "@@MODELDIR@@": shlex.quote(str(_model_dir(cfg, run_name).resolve())),
        "@@PY@@": shlex.quote(sys.executable),
        "@@PIMM@@": shlex.quote(_pimm_executable()),
        "@@MAXNOPROGRESS@@": "3",
        "@@HEAD_ARRAY@@": " ".join(shlex.quote(a) for a in head),
        "@@TAIL_ARRAY@@": " ".join(shlex.quote(a) for a in tail),
        "@@CHILD_ENV@@": CHILD_ENV,
    }
    script = _DRIVER_TEMPLATE
    for token, value in subs.items():
        script = script.replace(token, value)
    return script


# --------------------------------------------------------------------------- #
# scrontab block management (idempotent, per-run, preserves other entries)
# --------------------------------------------------------------------------- #
def _begin(run_name: str) -> str:
    return f"# >>> pimm-watchdog: {run_name} >>>"


def _end(run_name: str) -> str:
    return f"# <<< pimm-watchdog: {run_name} <<<"


def _read_scrontab() -> str:
    r = subprocess.run(["scrontab", "-l"], capture_output=True, text=True)
    # No crontab yet -> scrontab exits non-zero with a message on stderr.
    return r.stdout if r.returncode == 0 else ""


def _write_scrontab(text: str) -> None:
    text = text.strip("\n")
    if not text:
        subprocess.run(["scrontab", "-r"], capture_output=True, text=True)
        return
    r = subprocess.run(["scrontab", "-"], input=text + "\n", capture_output=True, text=True)
    if r.returncode != 0:
        raise SystemExit(f"failed to write scrontab:\n{r.stderr or r.stdout}")


def _strip_block(text: str, run_name: str) -> str:
    """Remove an existing pimm-watchdog block for run_name, if present."""
    begin, end = _begin(run_name), _end(run_name)
    lines = text.splitlines()
    out, skipping = [], False
    for line in lines:
        if line.strip() == begin:
            skipping = True
            continue
        if line.strip() == end:
            skipping = False
            continue
        if not skipping:
            out.append(line)
    return "\n".join(out)


def _build_block(cfg: dict[str, Any], run_name: str, driver_path: Path) -> str:
    wd = _watchdog_cfg(cfg)
    sd = state_dir(cfg, run_name).resolve()
    job = build_slurm_job_name(cfg, run_name)
    account = cfg.get("resources", {}).get("account")
    if not account:
        raise SystemExit(
            "watchdog: resources.account is required (scron's 'cron' QOS needs -A). "
            "Set it via --resources.account or the site config."
        )
    # scron submits under the `cron` QOS (login nodes); it requires an account and
    # caps walltime (1 day on NERSC), after which scron re-fires and resumes.
    return "\n".join(
        [
            _begin(run_name),
            f"#SCRON -q {wd['qos']}",
            f"#SCRON -A {account}",
            f"#SCRON -t {wd['time']}",
            f"#SCRON -J {job}-watchdog",
            f"#SCRON -o {sd / 'scron.%j.out'}",
            "#SCRON --open-mode=append",
            f"*/{int(wd['interval_min'])} * * * * {driver_path}",
            _end(run_name),
        ]
    )


def upsert_entry(cfg: dict[str, Any], run_name: str, driver_path: Path) -> None:
    current = _read_scrontab()
    stripped = _strip_block(current, run_name)
    block = _build_block(cfg, run_name, driver_path)
    combined = (stripped.strip("\n") + "\n\n" + block) if stripped.strip("\n") else block
    _write_scrontab(combined)


def remove_entry(run_name: str) -> bool:
    current = _read_scrontab()
    if _begin(run_name) not in current:
        return False
    _write_scrontab(_strip_block(current, run_name))
    return True


def list_entries() -> list[str]:
    prefix = "# >>> pimm-watchdog: "
    runs = []
    for line in _read_scrontab().splitlines():
        s = line.strip()
        if s.startswith(prefix) and s.endswith(">>>"):
            runs.append(s[len(prefix) : -len(" >>>")].strip())
    return runs


# --------------------------------------------------------------------------- #
# State / introspection (for `pimm watchdog ls|rm` -- config-free)
# --------------------------------------------------------------------------- #
def parsed_entries() -> list[dict[str, str]]:
    """Parse installed watchdog blocks straight from the scrontab (no config)."""
    entries: list[dict[str, str]] = []
    cur: dict[str, str] | None = None
    for line in _read_scrontab().splitlines():
        s = line.strip()
        if s.startswith("# >>> pimm-watchdog: ") and s.endswith(">>>"):
            cur = {"run": s[len("# >>> pimm-watchdog: ") : -len(" >>>")].strip()}
        elif cur is None:
            continue
        elif s.startswith("# <<< pimm-watchdog: "):
            cur.setdefault("state_dir", str(Path(cur.get("driver", "")).parent))
            entries.append(cur)
            cur = None
        elif s.startswith("#SCRON -J ") or s.startswith("#SCRON --job-name="):
            job = s.split("=", 1)[1] if "=" in s else s.split()[-1]
            cur["job"] = job[: -len("-watchdog")] if job.endswith("-watchdog") else job
        elif s.startswith("#SCRON -q ") or s.startswith("#SCRON --qos="):
            cur["qos"] = s.split("=", 1)[1] if "=" in s else s.split()[-1]
        elif s and not s.startswith("#"):  # the cron schedule line: `*/5 * * * * <driver>`
            cur["driver"] = s.split()[-1]
    return entries


def dir_state(state_dir: str, job: str) -> str:
    sd = Path(state_dir)
    if (sd / "DONE").exists():
        return "done"
    if (sd / "FAILED").exists():
        return "FAILED"
    r = subprocess.run(
        ["squeue", "-h", "-o", "%T", "-u", os.environ.get("USER", ""), "-n", job],
        capture_output=True,
        text=True,
    )
    states = {s.strip() for s in r.stdout.split()}
    if "RUNNING" in states:
        return "running"
    if states:
        return "queued"
    return "idle"


# --------------------------------------------------------------------------- #
# Entry point used by run_submit
# --------------------------------------------------------------------------- #
def install_watchdog(
    cfg: dict[str, Any],
    run_name: str,
    raw_argv: list[str],
    *,
    dry_run: bool = False,
    output: str | None = None,
) -> int:
    """Render the wrapper and (re)install this run's scron entry. Idempotent:
    replaces only this run's block, leaving other runs' watchdogs untouched."""
    sd = state_dir(cfg, run_name)
    driver_path = (sd / "driver.sh").resolve()
    script = render_driver_script(cfg, run_name, raw_argv)
    block = _build_block(cfg, run_name, driver_path)

    if dry_run:
        print(f"# watchdog wrapper -> {driver_path}\n{script}")
        print(f"# scrontab block:\n{block}")
        return 0

    sd.mkdir(parents=True, exist_ok=True)
    driver_path.write_text(script, encoding="utf-8")
    driver_path.chmod(0o755)
    # A fresh (re)install means "run this"; clear terminal markers from a prior life.
    for marker in ("DONE", "FAILED", "noprogress_count"):
        (sd / marker).unlink(missing_ok=True)

    if output:
        Path(output).write_text(script, encoding="utf-8")
        print(f"# wrote watchdog wrapper: {output}")

    upsert_entry(cfg, run_name, driver_path)
    wd = _watchdog_cfg(cfg)
    print(
        f"{'=' * 80}\n"
        f"Interactive chain watchdog installed for run: {run_name}\n"
        f"  driver:   {driver_path}\n"
        f"  scron:    every {wd['interval_min']} min under QOS '{wd['qos']}' "
        f"(starts within {wd['interval_min']} min)\n"
        f"  log:      {sd / 'driver.log'}\n"
        f"{'=' * 80}\n"
        "Every slot is interactive; the driver survives login-node reboots and resumes from checkpoint.\n"
        "Manage:\n"
        f"  pimm watchdog ls\n"
        f"  pimm watchdog rm {run_name}\n"
        f"  tail -f {sd / 'driver.log'}\n"
    )
    return 0
